#!/usr/bin/env bash
# redirect to a new page
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
link="https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4"
new_string="\trewrite ^\/redirect_me $link permanent;\n}"
sed -i "s/^}$/$new_string/" etc/nginx/sites-available/default
service niginx restart
