#!/usr/bin/env bash
# instal and configure haproxy load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo -e "frontend http\n\tbind *:80\n\tdefault_backend web-backend\n" > /etc/haproxy/haproxy.cfg
echo -e "backend web-backend\n\tbalance roundrobin\n \
\tserver 267440-web-01 54.209.208.34:80 check\n \
\tserver 267440-web-02 54.87.234.46:80 check\n" >> /etc/haproxy/haproxy.cfg
cat /etc/haproxy/haproxy.cfg.original >> /etc/haproxy/haproxy.cfg
service haproxy restart
